# Generated by Django 5.1.3 on 2025-05-04 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(blank=True, default='', max_length=1024, null=True)),
                ('mobile', models.CharField(blank=True, default='', max_length=1024, null=True)),
                ('email', models.CharField(blank=True, max_length=1024, null=True)),
                ('father_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('aadhar_no', models.CharField(blank=True, max_length=1024, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=1024, null=True)),
                ('image', models.CharField(blank=True, max_length=1024, null=True)),
                ('address', models.CharField(blank=True, max_length=1024, null=True)),
                ('pincode', models.CharField(blank=True, max_length=254, null=True)),
                ('is_aadhar_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_settings.city')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_settings.state')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('judgment', models.TextField(blank=True, null=True)),
                ('accused_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('victim_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('status', models.CharField(choices=[('filed', 'Case Filed'), ('under_investigation', 'Under Investigation'), ('charges_framed', 'Charges Framed'), ('trial', 'Trial in Progress'), ('awaiting_verdict', 'Awaiting Verdict'), ('judgment_pronounced', 'Judgment Pronounced'), ('convicted', 'Convicted'), ('acquitted', 'Acquitted'), ('closed', 'Case Closed'), ('appealed', 'Appealed to Higher Court'), ('withdrawn', 'Withdrawn'), ('settled', 'Settled Out of Court'), ('reopened', 'Reopened')], default='filed', max_length=124)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=128)),
                ('case_type', models.CharField(choices=[('criminal', 'Criminal'), ('civil', 'Civil'), ('family', 'Family'), ('labour', 'Labour'), ('consumer', 'Consumer'), ('land_dispute', 'Land Dispute'), ('corporate', 'Corporate'), ('tax', 'Tax'), ('environment', 'Environment'), ('constitutional', 'Constitutional'), ('cyber', 'Cyber Crime'), ('intellectual_property', 'Intellectual Property')], default='criminal', max_length=128)),
                ('case_subtype', models.CharField(blank=True, max_length=128, null=True)),
                ('number_of_parties', models.PositiveIntegerField(blank=True, null=True)),
                ('seriousness', models.CharField(blank=True, max_length=64, null=True)),
                ('sections', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=1024, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('previous_hearing_date', models.DateField(blank=True, null=True)),
                ('next_hearing_date', models.DateField(blank=True, null=True)),
                ('next_hearing_time', models.TimeField(blank=True, null=True)),
                ('prosecutor_lawyer', models.CharField(blank=True, max_length=1024, null=True)),
                ('defender_lawyer', models.CharField(blank=True, max_length=1024, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('court', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_settings.court')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='case_employee', to='admin_settings.employee')),
                ('judge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='case_judge', to='admin_settings.judge')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='case_user', to=settings.AUTH_USER_MODEL)),
                ('accused', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='case_accused', to='customer.customer')),
                ('victim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='case_victim', to='customer.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
